export enum UserDataStages {
  AWAITING_BIRTH_NAME = 'AWAITING_BIRTH_NAME',
  AWAITING_BIRTH_DATE = 'AWAITING_BIRTH_DATE',
  AWAITING_BIRTH_TIME = 'AWAITING_BIRTH_TIME',
  AWAITING_BIRTH_PLACE = 'AWAITING_BIRTH_PLACE',
}
